// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetWeb3Bourse.Data;

#nullable disable

namespace ProjetWeb3Bourse.Migrations
{
    [DbContext(typeof(BourseContext))]
    partial class ProjetWeb3BourseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetWeb3Bourse.Models.Bourse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("valeur")
                        .HasColumnType("float");

                    b.Property<double>("variation")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Bourse");
                });
#pragma warning restore 612, 618
        }
    }
}
